In [5]:
# Import of librairies
import pandas as pd

In [6]:
# Import of data
df_clothes = pd.read_excel("./Dataset/Clothes_table.xlsx", header=[1])

In [7]:
# Columns rename
df_clothes = df_clothes.rename(columns={"Noms":"name", "Photos" :"photos", "Description" : "descriptions"})

In [8]:
df_mood = pd.read_excel("./Dataset/Mood_table.xlsx")

In [9]:
df_mood = df_mood.drop(["Unnamed: 0"], axis=1)
df_mood


day_mood
0   Je suis fatiguée, et je sais que j'ai une gros...
1   Je suis en pleine forme pour mon entretien ave...
2   Il fait froid dehors, j'ai trop envie de reste...
3   Il fait trop beau et chaud, j'ai trop hâte d'a...
4   Je suis trop contente, aujourd'hui je vois Clé...
5   Journée shopping avec les copines, ça va être ...
6                     Trop dur de se lever ce matin….
7   J'ai une réunion tout à l'heure, je suis trop ...
8   J'ai bien dormi, je me sens reposée, je sens q...
9   Il pleut, je suis crevée, et j'ai loupé mon ré...
10  Ce boulot me soule, j'en ai trop marre, j'ai e...
11  Hâte d'aller au travail et de raconter mon wee...
12                                     J'ai trop faim
13              Je suis complétement à la bourre !!!!
14  Je trouve rien à me mettre, je dois me rachete...
15  Trop contente, je vois Nicolas au boulot, je v...

In [10]:
import torch

In [11]:
from transformers import CamembertModel, CamembertTokenizer
from transformers import CamembertConfig
# (Need to reload the model with new config)


In [12]:
tokenizer = CamembertTokenizer.from_pretrained('camembert-base')
camembert = CamembertModel.from_pretrained('camembert-base')


Some weights of the model checkpoint at camembert-base were not used when initializing CamembertModel: ['lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing CamembertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CamembertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [13]:
df_mood['tokenized_mood'] = ""

In [14]:
df_mood.loc[0]['tokenized_mood']=tokenizer.tokenize(df_mood.loc[0]['day_mood'])

In [15]:
for i in range (len(df_mood)):
    df_mood.loc[i]['tokenized_mood']=tokenizer.tokenize(df_mood.loc[i]['day_mood'])

In [16]:
df_mood['encoded_mood'] = ""

In [17]:
for i in range (len(df_mood)):
    df_mood.loc[i]['encoded_mood']=tokenizer.encode(df_mood.loc[i]['tokenized_mood'])
df_mood

day_mood  \
0   Je suis fatiguée, et je sais que j'ai une gros...   
1   Je suis en pleine forme pour mon entretien ave...   
2   Il fait froid dehors, j'ai trop envie de reste...   
3   Il fait trop beau et chaud, j'ai trop hâte d'a...   
4   Je suis trop contente, aujourd'hui je vois Clé...   
5   Journée shopping avec les copines, ça va être ...   
6                     Trop dur de se lever ce matin….   
7   J'ai une réunion tout à l'heure, je suis trop ...   
8   J'ai bien dormi, je me sens reposée, je sens q...   
9   Il pleut, je suis crevée, et j'ai loupé mon ré...   
10  Ce boulot me soule, j'en ai trop marre, j'ai e...   
11  Hâte d'aller au travail et de raconter mon wee...   
12                                     J'ai trop faim   
13              Je suis complétement à la bourre !!!!   
14  Je trouve rien à me mettre, je dois me rachete...   
15  Trop contente, je vois Nicolas au boulot, je v...   

                                       tokenized_mood  \
0   [▁Je, ▁suis, ▁fatiguée, ,, ▁et, ▁je, ▁sais, ▁q...   
1   [▁Je, ▁suis, ▁en, ▁pleine, ▁forme, ▁pour, ▁mon...   
2   [▁Il, ▁fait, ▁froid, ▁dehors, ,, ▁j, ', ai, ▁t...   
3   [▁Il, ▁fait, ▁trop, ▁beau, ▁et, ▁chaud, ,, ▁j,...   
4   [▁Je, ▁suis, ▁trop, ▁contente, ,, ▁aujourd, ',...   
5   [▁Journée, ▁shopping, ▁avec, ▁les, ▁copines, ,...   
6   [▁Trop, ▁dur, ▁de, ▁se, ▁lever, ▁ce, ▁matin, ....   
7   [▁J, ', ai, ▁une, ▁réunion, ▁tout, ▁à, ▁l, ', ...   
8   [▁J, ', ai, ▁bien, ▁dormi, ,, ▁je, ▁me, ▁sens,...   
9   [▁Il, ▁pleut, ,, ▁je, ▁suis, ▁cre, vée, ,, ▁et...   
10  [▁Ce, ▁boulot, ▁me, ▁soul, e, ,, ▁j, ', en, ▁a...   
11  [▁H, ât, e, ▁d, ', aller, ▁au, ▁travail, ▁et, ...   
12                          [▁J, ', ai, ▁trop, ▁faim]   
13  [▁Je, ▁suis, ▁complétement, ▁à, ▁la, ▁bourre, ...   
14  [▁Je, ▁trouve, ▁rien, ▁à, ▁me, ▁mettre, ,, ▁je...   
15  [▁Trop, ▁contente, ,, ▁je, ▁vois, ▁Nicolas, ▁a...   

                                         encoded_mood  
0   [5, 100, 146, 20644, 7, 14, 50, 555, 27, 76, 1...  
1   [5, 100, 146, 22, 1430, 431, 24, 129, 3284, 42...  
2   [5, 69, 82, 1815, 2058, 7, 76, 11, 73, 237, 79...  
3   [5, 69, 82, 237, 670, 14, 1688, 7, 76, 11, 73,...  
4   [5, 100, 146, 237, 4062, 7, 405, 11, 265, 50, ...  
5   [5, 7731, 10603, 42, 19, 15140, 7, 136, 198, 9...  
6     [5, 6703, 2498, 8, 48, 4590, 44, 823, 57, 9, 6]  
7   [5, 121, 11, 73, 28, 2207, 66, 15, 17, 11, 113...  
8   [5, 121, 11, 73, 72, 22637, 7, 50, 103, 437, 3...  
9   [5, 69, 23291, 7, 50, 146, 5589, 10895, 7, 14,...  
10  [5, 148, 3822, 103, 16871, 35, 7, 76, 11, 90, ...  
11  [5, 454, 3509, 35, 18, 11, 1655, 36, 225, 14, ...  
12                     [5, 121, 11, 73, 237, 5769, 6]  
13       [5, 100, 146, 24855, 15, 13, 23035, 6500, 6]  
14  [5, 100, 396, 254, 15, 103, 328, 7, 50, 1749, ...  
15  [5, 6703, 4062, 7, 50, 1460, 2289, 36, 3822, 7...

In [18]:
df_clothes['tokenized_clothes'] = ""
df_clothes = df_clothes.drop(["Unnamed: 0"], axis=1)

In [19]:
df_clothes.loc[0]['tokenized_clothes']=tokenizer.tokenize(df_clothes.loc[0]['descriptions'])

In [20]:
for i in range (len(df_clothes)):
    df_clothes.loc[i]['tokenized_clothes']=tokenizer.tokenize(df_clothes.loc[i]['descriptions'])

In [21]:
df_clothes['encoded_clothes'] = ""

In [22]:
for i in range (len(df_clothes)):
    df_clothes.loc[i]['encoded_clothes']=tokenizer.encode(df_clothes.loc[i]['tokenized_clothes'])
df_clothes

name                                             photos  \
0      Tee-shirt_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
1           Pull_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
2           Pull_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
3          Veste_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
4         Gillet_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
5      Robe_pull_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
6          Veste_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
7            Short  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
8        Chemisier  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
9      Tee-shirt_3  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
10     Chemisier_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
11         Short_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
12     Jupe-longue  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
13  Robe-de-soirée  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
14   Jupe-courte_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
15      Pantalon_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
16          Jean_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
17     Debardeur_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
18     Debardeur_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
19     Debardeur_3  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   

                                         descriptions  \
0   J'ai acheté ce tshirt pour les beaux jours, po...   
1   J'ai acheté ce pull pour le porter en mi saiso...   
2   J'aime le côté rock de ce pull. J'ai envie de ...   
3   Je voulais un classique rock intemporel, que l...   
4   J'aime le côté ethnique et loose de ce gilet. ...   
5   J'ai acheté cette robe pour me sentir féminine...   
6   Je voulais une veste en jean légère, apportant...   
7   Je voulais un short en jean pour me sentir à l...   
8   Je voulais une chemise classique mais conforta...   
9   Je cherchais un tshirt avec capuche pour le cô...   
10  J'ai acheté cette blouse pour avoir des tenues...   
11  Je cherchais un short en jean pour le porter e...   
12  J'ai acheté cette jupe longue pour le coté con...   
13  Je cherchais une robe assez classique, que je ...   
14  J'ai acheté cette jupe courte noire en jean po...   
15  Je cherchais un pantalon confortable quand il ...   
16  Je cherchais un jean pour remplacer un ancien ...   
17  Je cherchais un débardeur à fines bretelles po...   
18  Je cherchais un débardeur à large bretelle pou...   
19  Je cherchais un débardeur très simple avec un ...   

                                    tokenized_clothes  \
0   [▁J, ', ai, ▁acheté, ▁ce, ▁t, shirt, ▁pour, ▁l...   
1   [▁J, ', ai, ▁acheté, ▁ce, ▁pull, ▁pour, ▁le, ▁...   
2   [▁J, ', aime, ▁le, ▁côté, ▁rock, ▁de, ▁ce, ▁pu...   
3   [▁Je, ▁voulais, ▁un, ▁classique, ▁rock, ▁intem...   
4   [▁J, ', aime, ▁le, ▁côté, ▁ethnique, ▁et, ▁l, ...   
5   [▁J, ', ai, ▁acheté, ▁cette, ▁robe, ▁pour, ▁me...   
6   [▁Je, ▁voulais, ▁une, ▁veste, ▁en, ▁jean, ▁lég...   
7   [▁Je, ▁voulais, ▁un, ▁short, ▁en, ▁jean, ▁pour...   
8   [▁Je, ▁voulais, ▁une, ▁chemise, ▁classique, ▁m...   
9   [▁Je, ▁cherchais, ▁un, ▁t, shirt, ▁avec, ▁capu...   
10  [▁J, ', ai, ▁acheté, ▁cette, ▁blouse, ▁pour, ▁...   
11  [▁Je, ▁cherchais, ▁un, ▁short, ▁en, ▁jean, ▁po...   
12  [▁J, ', ai, ▁acheté, ▁cette, ▁jupe, ▁longue, ▁...   
13  [▁Je, ▁cherchais, ▁une, ▁robe, ▁assez, ▁classi...   
14  [▁J, ', ai, ▁acheté, ▁cette, ▁jupe, ▁courte, ▁...   
15  [▁Je, ▁cherchais, ▁un, ▁pantalon, ▁confortable...   
16  [▁Je, ▁cherchais, ▁un, ▁jean, ▁pour, ▁remplace...   
17  [▁Je, ▁cherchais, ▁un, ▁débardeur, ▁à, ▁fines,...   
18  [▁Je, ▁cherchais, ▁un, ▁débardeur, ▁à, ▁large,...   
19  [▁Je, ▁cherchais, ▁un, ▁débardeur, ▁très, ▁sim...   

                                      encoded_clothes  
0   [5, 121, 11, 73, 2824, 4

In [23]:
encoded_sentence = torch.tensor(df_clothes.loc[0]['encoded_clothes']).unsqueeze(0)
encoded_sentence

tensor([[    5,   121,    11,    73,  2824,    44,   271,  5728,    24,    19,
          1999,   274,     7,   351,   103, 18779,    22,   401,    47,   223,
            20,   784,     6]])

In [24]:
embeddings= camembert(encoded_sentence,output_hidden_states=True)
embeddings


BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.0098,  0.0228,  0.0854,  ..., -0.1018,  0.0165,  0.0489],
         [ 0.0321, -0.1783,  0.0601,  ..., -0.2533,  0.0612, -0.1117],
         [-0.0933, -0.1538,  0.2662,  ..., -0.1116,  0.0857,  0.0532],
         ...,
         [ 0.0388, -0.1852, -0.1043,  ..., -0.1657,  0.0861,  0.0603],
         [ 0.0947,  0.0485, -0.1613,  ..., -0.0435,  0.0205,  0.0251],
         [-0.0643,  0.0578,  0.0993,  ..., -0.0654, -0.0271,  0.0244]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-1.0487e-01,  1.1067e-01,  1.4064e-02,  1.4861e-02, -7.5464e-04,
          1.6243e-01,  3.3965e-02,  1.0208e-01, -4.6147e-02, -2.0813e-02,
          6.7648e-02, -1.5502e-02, -5.1616e-02, -5.8808e-02, -9.5780e-02,
         -1.6172e-02, -5.3142e-02,  1.2655e-01, -2.9039e-03, -3.4727e-02,
         -6.7128e-02, -5.9631e-04,  1.1961e-01,  7.9285e-02, -7.1805e-02,
          3.3155e-02,  5.5372e-02,  9.5790e-02, -1.3638e-01,  4.703

In [25]:
last_hidden_states = embeddings.hidden_states[-1]
last_hidden_states

tensor([[[-0.0098,  0.0228,  0.0854,  ..., -0.1018,  0.0165,  0.0489],
         [ 0.0321, -0.1783,  0.0601,  ..., -0.2533,  0.0612, -0.1117],
         [-0.0933, -0.1538,  0.2662,  ..., -0.1116,  0.0857,  0.0532],
         ...,
         [ 0.0388, -0.1852, -0.1043,  ..., -0.1657,  0.0861,  0.0603],
         [ 0.0947,  0.0485, -0.1613,  ..., -0.0435,  0.0205,  0.0251],
         [-0.0643,  0.0578,  0.0993,  ..., -0.0654, -0.0271,  0.0244]]],
       grad_fn=<NativeLayerNormBackward0>)

In [26]:
a = last_hidden_states[0,0,:]

In [27]:
df_clothes["CLS"] =""
df_clothes

name                                             photos  \
0      Tee-shirt_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
1           Pull_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
2           Pull_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
3          Veste_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
4         Gillet_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
5      Robe_pull_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
6          Veste_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
7            Short  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
8        Chemisier  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
9      Tee-shirt_3  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
10     Chemisier_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
11         Short_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
12     Jupe-longue  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
13  Robe-de-soirée  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
14   Jupe-courte_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
15      Pantalon_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
16          Jean_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
17     Debardeur_1  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
18     Debardeur_2  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   
19     Debardeur_3  C:\Users\fanny\OneDrive\Bureau\Jedha\Final_pro...   

                                         descriptions  \
0   J'ai acheté ce tshirt pour les beaux jours, po...   
1   J'ai acheté ce pull pour le porter en mi saiso...   
2   J'aime le côté rock de ce pull. J'ai envie de ...   
3   Je voulais un classique rock intemporel, que l...   
4   J'aime le côté ethnique et loose de ce gilet. ...   
5   J'ai acheté cette robe pour me sentir féminine...   
6   Je voulais une veste en jean légère, apportant...   
7   Je voulais un short en jean pour me sentir à l...   
8   Je voulais une chemise classique mais conforta...   
9   Je cherchais un tshirt avec capuche pour le cô...   
10  J'ai acheté cette blouse pour avoir des tenues...   
11  Je cherchais un short en jean pour le porter e...   
12  J'ai acheté cette jupe longue pour le coté con...   
13  Je cherchais une robe assez classique, que je ...   
14  J'ai acheté cette jupe courte noire en jean po...   
15  Je cherchais un pantalon confortable quand il ...   
16  Je cherchais un jean pour remplacer un ancien ...   
17  Je cherchais un débardeur à fines bretelles po...   
18  Je cherchais un débardeur à large bretelle pou...   
19  Je cherchais un débardeur très simple avec un ...   

                                    tokenized_clothes  \
0   [▁J, ', ai, ▁acheté, ▁ce, ▁t, shirt, ▁pour, ▁l...   
1   [▁J, ', ai, ▁acheté, ▁ce, ▁pull, ▁pour, ▁le, ▁...   
2   [▁J, ', aime, ▁le, ▁côté, ▁rock, ▁de, ▁ce, ▁pu...   
3   [▁Je, ▁voulais, ▁un, ▁classique, ▁rock, ▁intem...   
4   [▁J, ', aime, ▁le, ▁côté, ▁ethnique, ▁et, ▁l, ...   
5   [▁J, ', ai, ▁acheté, ▁cette, ▁robe, ▁pour, ▁me...   
6   [▁Je, ▁voulais, ▁une, ▁veste, ▁en, ▁jean, ▁lég...   
7   [▁Je, ▁voulais, ▁un, ▁short, ▁en, ▁jean, ▁pour...   
8   [▁Je, ▁voulais, ▁une, ▁chemise, ▁classique, ▁m...   
9   [▁Je, ▁cherchais, ▁un, ▁t, shirt, ▁avec, ▁capu...   
10  [▁J, ', ai, ▁acheté, ▁cette, ▁blouse, ▁pour, ▁...   
11  [▁Je, ▁cherchais, ▁un, ▁short, ▁en, ▁jean, ▁po...   
12  [▁J, ', ai, ▁acheté, ▁cette, ▁jupe, ▁longue, ▁...   
13  [▁Je, ▁cherchais, ▁une, ▁robe, ▁assez, ▁classi...   
14  [▁J, ', ai, ▁acheté, ▁cette, ▁jupe, ▁courte, ▁...   
15  [▁Je, ▁cherchais, ▁un, ▁pantalon, ▁confortable...   
16  [▁Je, ▁cherchais, ▁un, ▁jean, ▁pour, ▁remplace...   
17  [▁Je, ▁cherchais, ▁un, ▁débardeur, ▁à, ▁fines,...   
18  [▁Je, ▁cherchais, ▁un, ▁débardeur, ▁à, ▁large,...   
19  [▁Je, ▁cherchais, ▁un, ▁débardeur, ▁très, ▁sim...   

                                      encoded_clothes CLS  
0   [5, 121, 11, 73, 282

In [28]:
for i in range (len(df_clothes)):
    encoded_sentence = torch.tensor(df_clothes.loc[i]['encoded_clothes']).unsqueeze(0)
    embeddings= camembert(encoded_sentence,output_hidden_states=True)
    last_hidden_states = embeddings.hidden_states[-1]
    df_clothes.loc[i]["CLS"] = last_hidden_states[0,0,:]

In [29]:
df_clothes.loc[0]["CLS"]

tensor([-9.7810e-03,  2.2771e-02,  8.5406e-02, -1.5715e-02, -4.6360e-03,
        -7.9522e-03,  4.1203e-02,  2.9701e-01, -1.2629e-02,  9.1869e-02,
         1.9277e-02,  1.2628e-01, -7.8062e-02,  1.4661e-01,  3.0248e-01,
        -3.1359e-02,  2.7505e-02, -8.6666e-02,  8.7040e-02, -1.3925e-01,
         4.9970e-02, -8.7114e-02,  7.2085e-02, -3.5607e-01,  1.9320e-01,
        -1.8871e-01,  6.0448e-03, -5.5312e-02, -1.9672e-03, -1.9855e-02,
         9.0787e-02, -2.5221e-01,  1.5804e-01,  1.6815e-01,  1.2524e-01,
        -1.5902e-01, -1.0924e-01,  1.6250e-01, -5.2118e-02, -6.0078e-03,
        -2.1053e-01,  1.2944e-01,  1.2434e-01, -1.6526e-02,  1.2068e-01,
         1.9600e-01, -2.1557e-01,  4.8482e-02, -5.8431e-02,  4.7736e-02,
         5.2510e-02, -6.7334e-02, -5.5265e-01,  1.2243e-01,  1.5968e-02,
        -1.8564e-02, -1.4336e-02, -5.7622e-03,  1.4700e-01,  2.5943e-03,
         3.1304e-02,  6.2449e-02,  2.3951e-02, -2.5363e-02,  1.9116e-02,
         1.2003e-01, -8.4499e-02,  1.4118e-01,  3.2

In [30]:
df_mood["CLS"] =""
df_mood

day_mood  \
0   Je suis fatiguée, et je sais que j'ai une gros...   
1   Je suis en pleine forme pour mon entretien ave...   
2   Il fait froid dehors, j'ai trop envie de reste...   
3   Il fait trop beau et chaud, j'ai trop hâte d'a...   
4   Je suis trop contente, aujourd'hui je vois Clé...   
5   Journée shopping avec les copines, ça va être ...   
6                     Trop dur de se lever ce matin….   
7   J'ai une réunion tout à l'heure, je suis trop ...   
8   J'ai bien dormi, je me sens reposée, je sens q...   
9   Il pleut, je suis crevée, et j'ai loupé mon ré...   
10  Ce boulot me soule, j'en ai trop marre, j'ai e...   
11  Hâte d'aller au travail et de raconter mon wee...   
12                                     J'ai trop faim   
13              Je suis complétement à la bourre !!!!   
14  Je trouve rien à me mettre, je dois me rachete...   
15  Trop contente, je vois Nicolas au boulot, je v...   

                                       tokenized_mood  \
0   [▁Je, ▁suis, ▁fatiguée, ,, ▁et, ▁je, ▁sais, ▁q...   
1   [▁Je, ▁suis, ▁en, ▁pleine, ▁forme, ▁pour, ▁mon...   
2   [▁Il, ▁fait, ▁froid, ▁dehors, ,, ▁j, ', ai, ▁t...   
3   [▁Il, ▁fait, ▁trop, ▁beau, ▁et, ▁chaud, ,, ▁j,...   
4   [▁Je, ▁suis, ▁trop, ▁contente, ,, ▁aujourd, ',...   
5   [▁Journée, ▁shopping, ▁avec, ▁les, ▁copines, ,...   
6   [▁Trop, ▁dur, ▁de, ▁se, ▁lever, ▁ce, ▁matin, ....   
7   [▁J, ', ai, ▁une, ▁réunion, ▁tout, ▁à, ▁l, ', ...   
8   [▁J, ', ai, ▁bien, ▁dormi, ,, ▁je, ▁me, ▁sens,...   
9   [▁Il, ▁pleut, ,, ▁je, ▁suis, ▁cre, vée, ,, ▁et...   
10  [▁Ce, ▁boulot, ▁me, ▁soul, e, ,, ▁j, ', en, ▁a...   
11  [▁H, ât, e, ▁d, ', aller, ▁au, ▁travail, ▁et, ...   
12                          [▁J, ', ai, ▁trop, ▁faim]   
13  [▁Je, ▁suis, ▁complétement, ▁à, ▁la, ▁bourre, ...   
14  [▁Je, ▁trouve, ▁rien, ▁à, ▁me, ▁mettre, ,, ▁je...   
15  [▁Trop, ▁contente, ,, ▁je, ▁vois, ▁Nicolas, ▁a...   

                                         encoded_mood CLS  
0   [5, 100, 146, 20644, 7, 14, 50, 555, 27, 76, 1...      
1   [5, 100, 146, 22, 1430, 431, 24, 129, 3284, 42...      
2   [5, 69, 82, 1815, 2058, 7, 76, 11, 73, 237, 79...      
3   [5, 69, 82, 237, 670, 14, 1688, 7, 76, 11, 73,...      
4   [5, 100, 146, 237, 4062, 7, 405, 11, 265, 50, ...      
5   [5, 7731, 10603, 42, 19, 15140, 7, 136, 198, 9...      
6     [5, 6703, 2498, 8, 48, 4590, 44, 823, 57, 9, 6]      
7   [5, 121, 11, 73, 28, 2207, 66, 15, 17, 11, 113...      
8   [5, 121, 11, 73, 72, 22637, 7, 50, 103, 437, 3...      
9   [5, 69, 23291, 7, 50, 146, 5589, 10895, 7, 14,...      
10  [5, 148, 3822, 103, 16871, 35, 7, 76, 11, 90, ...      
11  [5, 454, 3509, 35, 18, 11, 1655, 36, 225, 14, ...      
12                     [5, 121, 11, 73, 237, 5769, 6]      
13       [5, 100, 146, 24855, 15, 13, 23035, 6500, 6]      
14  [5, 100, 396, 254, 15, 103, 328, 7, 50, 1749, ...      
15  [5, 6703, 4062, 7, 50, 1460, 2289, 36, 3822, 7...

In [31]:
for i in range (len(df_mood)):
    encoded_sentence = torch.tensor(df_mood.loc[i]['encoded_mood']).unsqueeze(0)
    embeddings= camembert(encoded_sentence,output_hidden_states=True)
    last_hidden_states = embeddings.hidden_states[-1]
    df_mood.loc[i]["CLS"] = last_hidden_states[0,0,:]

In [38]:
X = df_mood.loc[1]["CLS"].detach().numpy().reshape(1, -1)
Y = df_clothes.loc[2]["CLS"].detach().numpy().reshape(1, -1)

In [39]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity
test_cos_similarity = sklearn.metrics.pairwise.cosine_similarity(X,Y)
test_cos_similarity

array([[0.90832895]], dtype=float32)

In [44]:
X1 = df_mood.loc[7]["CLS"].detach().numpy().reshape(1, -1)
X2 = df_mood.loc[4]["CLS"].detach().numpy().reshape(1, -1)
X3 = df_mood.loc[2]["CLS"].detach().numpy().reshape(1, -1)
Y1 = df_clothes.loc[9]["CLS"].detach().numpy().reshape(1, -1)

In [48]:
test_cos_similarity1 = sklearn.metrics.pairwise.cosine_similarity(X1,Y1)
test_cos_similarity1

array([[0.924955]], dtype=float32)

In [49]:
test_cos_similarity2 = sklearn.metrics.pairwise.cosine_similarity(X2,Y1)
test_cos_similarity2

array([[0.91995025]], dtype=float32)

In [50]:
test_cos_similarity3 = sklearn.metrics.pairwise.cosine_similarity(X3,Y1)
test_cos_similarity3

array([[0.9401429]], dtype=float32)